post:
  toc:
    enable: true
    expand_all: true
    placement: right
    headingSelector: "h1,h2,h3,h4,h5,h6"
    collapse_depth: 0
  mermaid:
    enable: true
    specific: false
    options: { theme: 'default' }

index:
  slogan:
    enable: true
    text: rebibabo的博客笔记

navbar:
  blog_title: 主页
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill', name: '首页' }
    - { key: 'posts', link: '/posts/', icon: 'iconfont icon-archive-fill', name: '文章' }
    - { key: 'category', link: '/categories/', icon: 'iconfont icon-category-fill', name: '分类' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill', name: '标签' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: '关于' }

footer:
  content: ''
  statistics:
    enable: false
  beian:
    enable: false