post:
  toc:
    enable: true
    expand_all: true
    placement: right
    headingSelector: "h1,h2,h3,h4,h5,h6"
    collapse_depth: 0
  mermaid:
    enable: true
    specific: false
    options: { theme: 'default' }
  post_order_by: "source"

index:
  slogan:
    enable: true
    text: rebibabo的博客笔记

navbar:
  blog_title: 主页
  menu:
    - { key: 'home', link: '/series/', icon: 'iconfont icon-home-fill', name: '首页' }
    # - { key: 'posts', link: '/posts/', icon: 'iconfont icon-archive-fill', name: '文章' }
    # - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill', name: '标签' }
    # - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill', name: '关于' }

footer:
  content: ''
  statistics:
    enable: false
  beian:
    enable: false

custom_css:
  - /css/custom.css

custom_js:
  - /js/back-to-category.js

static_prefix:
  anchor: https://cdn.jsdelivr.net/npm/anchor-js@5.0.0/
  github_markdown: https://cdn.jsdelivr.net/npm/github-markdown-css@4.0.0/
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/
  bootstrap: https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/
  prismjs: https://cdn.jsdelivr.net/npm/prismjs@1.29.0/
  tocbot: https://cdn.jsdelivr.net/npm/tocbot@4.20.1/dist/
  typed: https://cdn.jsdelivr.net/npm/typed.js@2.0.12/dist/
  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/
  nprogress: https://cdn.jsdelivr.net/npm/nprogress@0.2.0/
  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/
  mermaid: https://cdn.jsdelivr.net/npm/mermaid@11/dist/