graph LR
    subgraph Core1["Core 1"]
        direction LR
        S1["State: Shared<br>count = 0"]
    end
    subgraph Core2["Core 2"]
        direction LR
        S2["State: Shared<br>count = 0"]
    end